### ISSUE TITLE
Loss equations 7-9 :: conditioning on q

### ISSUE THREAD

**Issue by Mirmix** [prstrive/UniMVSNet#10]
Hi, thanks for making your works publicly available. I enjoyed going through your paper and "loss" code. I found a couple of things unclear for me regarding the loss, I will be glad if you will bring some clarifications. 

In your paper, you are mentioning that **q** is a continuous target that has a domain of [0,1]. But in the *Eq 7,8,9* in your system equations, you are conditioning your equations based on **q** *> 0* . I have checked your code where you are implementing the loss, as far as I understand you are conditioning your equations based on the condition of if  **q** ∈ *[u, u+interval]*

So in the *Eq 7,8,9*,  do you actually condition based on if the right interval is found? Or is it my wrong misinterpretations?

**Comment by prstrive** [comment]
You can explain it this way. But the range of the generated **q**  is *[0,1]*, and **q** *> 0* only under the condition of the right interval, you can refer to [here](https://github.com/prstrive/UniMVSNet/blob/7c1c9862cc6f2eb0b74c0569d58826d9416195b5/loss.py#L67).
