### ISSUE TITLE
about F-score on tanksandtemples

### ISSUE THREAD

**Issue by CC9310** [prstrive/UniMVSNet#11]
I have a problem on the tanks dataset:
for all 8 scenes, the private testing result is 
79.61	65.66	54.16	59.51	62.24	60.90	57.61	54.59

i follow the author's resconstruction configuration, while there is a large margin compare with the author's result, whether i miss something important?

**Comment by prstrive** [comment]
I have limited ideas about the reason only from this succinct statement. Maybe there are something wrong on environment or fusion configuration?

**Comment by CC9310** [comment]
@prstrive thanks for your respond, i will recheck the depth estimation process. 🙂
