### ISSUE TITLE
About abs_depthloss

### ISSUE THREAD

**Issue by Sun-Xinnnnn** [prstrive/UniMVSNet#16]
Hello, thank you very much for your code. May I ask how to check the absolute depth error in the training process？

**Comment by prstrive** [comment]
We only report the threshold error (Th2, Th4 or Th8), and you can insert the abs_error into the training process easily like (depth_gt[mask] - depth_est[mask]).asb().mean()

**Comment by Sun-Xinnnnn** [comment]
> We only report the threshold error (Th2, Th4 or Th8), and you can insert the abs_error into the training process easily like (depth_gt[mask] - depth_est[mask]).asb().mean()

thanks ：）

**Comment by Sun-Xinnnnn** [comment]
> We only report the threshold error (Th2, Th4 or Th8), and you can insert the abs_error into the training process easily like (depth_gt[mask] - depth_est[mask]).asb().mean()

What is your Abs depth err value? Mine seems a little big.
