### ISSUE TITLE
The result on ETH3D dataset

### ISSUE THREAD

**Issue by CanCanZeng** [prstrive/UniMVSNet#4]
Hi, thank you for opening this great project!
I tested this algorithm on Tandks and Temples dataset, the result is really nice! 
But when I tried on ETH3D dataset, the result is not so good, have you tested on ETH3D dataset? The checkpoint I used is the provided model on Tanks and Temples.

**Comment by prstrive** [comment]
Sorry, we didn't experiment with ETH3D. We think the reason for the suboptimal should be related to the point cloud filtering and fusion configuration, which you can tune appropriately according to the latest paper.

**Comment by CanCanZeng** [comment]
Hi, I tried different fusion strategy (ACMP and COLAMP), and truned fusion parameters in UniMVSNet, but all of these methods could not produce very nice result like in Tanks and Temples dataset. I mean, the result is still good, but not SOTA, is it reasonable?

**Comment by prstrive** [comment]
Maybe you can try the dynamic consistency checking strategy mentioned in [EPP-MVSNet](https://openaccess.thecvf.com/content/ICCV2021/papers/Ma_EPP-MVSNet_Epipolar-Assembling_Based_Depth_Prediction_for_Multi-View_Stereo_ICCV_2021_paper.pdf).
