### ISSUE TITLE
The winner-take-all selection

### ISSUE THREAD

**Issue by DIVE128** [prstrive/UniMVSNet#6]
Hellow, thanks for your great work and contribution. The unification applies winner-take-all selection as the basis to generate the depth map for the next finner stage. However, torch.max() is a non-differentiable operation and the parameters in 3D-CNN would be optimized except the parameters w.r.t the selected depth hypothesis. How do the gradients backward in this case?

**Comment by prstrive** [comment]
You are right! So we optimize the model through directly constraining the cost volume, but not the depth. You can refer to our paper or [here](https://github.com/prstrive/UniMVSNet/blob/7c1c9862cc6f2eb0b74c0569d58826d9416195b5/loss.py#L77) for more details.

**Comment by DIVE128** [comment]
Thanks a lot.
