### ISSUE TITLE
the results in Tanks and Temples

### ISSUE THREAD

**Issue by xingyi-li** [prstrive/UniMVSNet#7]
Thanks for your generous open source. We apply **unimvsnet_blendedmvs.ckpt** to reproduce the results of Tanks and Temples via **scripts/tank_test.sh**. Results are approaching in **advanced** while those of **intermediate** drop considerably. Is there any different setting between  **intermediate** and **advanced**，e.g., inverse depth, num_view, ndepths, interval_ratio ? 

The full results are as follow:

F-score: 

Auditorium: 27.28
Ballroom: 44.05
Courtroom: 39.13
Family: 34.35
Francis: 24.06
Horse: 06.13
Lighthouse: 58.74
M60: 57.29
Museum: 52.20
Palace: 32.27
Panther: 57.88
Playground: 57.57
Temple: 33.45
Train: 45.85
------------------
Mean intermediate: 42.73
Mean advanced: 38.06

**Comment by prstrive** [comment]
I guess you may not use the short depth range version of the camera parameters in Intermediate set as we described [here](https://github.com/prstrive/UniMVSNet#4-tanks-and-temples-dataset).
