### ISSUE TITLE
Convergence speed.

### ISSUE THREAD

**Issue by DIVE128** [prstrive/UniMVSNet#8]
Hello,  we train with a "unification"  and  “regression”  strategy respectively.  Abs depth err of "unification" in both avg train and 
 ave test  is higher than that of “regression” at the first few epoches. Is it normal to converge slower for "unification" strategy？

**Comment by prstrive** [comment]
Just looking at the error of the depth map, "unification" does drop slower than “regression”. But from our experience, when the error of depth map decreases to a certain level, the point cloud reconstruction quality does not get better as the depth map error decreases.

**Comment by DIVE128** [comment]
Thanks a lot.  A recent confusion is that "classication" compares prob volumes with supervision signals. From your experience, is it very different in the point cloud reconstruction to use  pure prob_volume_pre, softmax (prob_volume_pre ), or sigmoid (prob_volume_pre) when training?

**Comment by prstrive** [comment]
I think so!

**Comment by zhang-snowy** [comment]
What is the Abs depth err? Mine seems a little big.

**Comment by Sun-Xinnnnn** [comment]
What is your Abs depth err value? Mine seems a little big.
